config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :users, only: [:index, :new, :create, :edit, :update]
  resources :groups, only: [:index, :new, :create, :destroy] do
    resources :rooms, only:[:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :rooms, dependent: :destroy

  validates :group_name, presence: true
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 0, name: '下記から選んでください' },
    { id: 1, name: '施設長' },
    { id: 2, name: '介護主任' },
    { id: 3, name: 'ユニットリーダー' },
    { id: 4, name: '介護士' },
    { id: 5, name: '看護師' },
    { id: 6, name: '管理栄養士' },
    { id: 7, name: '生活相談員' },
    { id: 8, name: '機能訓練士' },
    { id: 9, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_one_attached :image

  validates :text, presence: true, unless: :was_attaced?

  def was_attaced?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position

  validates :name, presence: true
  validates :position_id, numericality: { other_than: 0 }

  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :rooms
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  before_action :authenticate_user!
  before_action :basic_auth

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :position_id, :email, :password])
    end

    def basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV["BASIC_AUTH_USER2"] && password == ENV["BASIC_AUTH_PASSWORD2"] 
      end
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to root_path
  end

  private

  def group_params
    params.require(:group).permit(:group_name, user_ids: [])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @room = Room.new
    @group = Group.find(params[:group_id])
    @rooms = @group.rooms.includes(:user)
  end

  def create
    @group = Group.find(params[:group_id])
    @room = @group.rooms.new(room_params)
    if @room.save
      redirect_to group_rooms_path(@group)
    else
      @rooms = @group.rooms.includes(:user)
      render :index
    end
  end

  private

  def room_params
    params.require(:room).permit(:text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order("created_at DESC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to root_path
      else
        render :new
      end
    end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path      
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :position_id, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "rooms/side_bar" %>
  </div>
</div>

app/views/groups/new.html.erb
<div class='chat-room-form'>
  <h1>新規要件</h1>
  <%=form_with model: @group, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :要件, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :group_name, class: 'chat__room_name chat-room-form__input', placeholder: '要件を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>メンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <div class='test'>
          <%= collection_check_boxes(:group, :user_ids, User.all, :id, :name) %>
        </div>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatpoolApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @group.group_name%>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "削除", group_path(@group), method: :delete, data: {confirm: '削除しますか？'} %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'room', collection: @rooms %>
</div>

<%= form_with model: [@group, @room], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :text, class: 'form-message', placeholder: 'メッセージを入力して下さい' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/rooms/_room.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= room.user.name %>
      <%= room.user.position.name %>
    </div>
    <div class="message-date">
      <%= l room.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= room.text %>
    </div>
    <%= image_tag room.image.variant(resize: '500x500'), class: 'message-image' if room.image.attached? %>
  </div>
</div>

app/views/rooms/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user)%>
  </div>
  <div class="create-group">
    <%= link_to "要件を作成する", new_group_path %>
  </div>
</div>

<div class="rooms">
  <% current_user.groups.each do |room| %>
    <div class="subject">
      <div class="subject-name">
        <%= link_to room.group_name, group_rooms_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :position%>
          </div>
          <%= f.collection_select(:position_id, Position.all, :id, :name, {}, {class:"select-box"}) %>
        </div>
        
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>